spring:
    mvc:
        view:
            prefix: /WEB-INF/view/
            suffix: .jsp
    datasource:
        url: jdbc:postgresql://localhost:5432/blank
        username: dbuser
        password: dbpass
        driver-class-name: org.postgresql.Driver
